version: 2

models:
  - name: hub_account
    description: Hub table for Account entity
    columns:
      - name: account_pk_hash
        description: Hash representation of the business key
        tests:
          - not_null
          - unique
      - name: account_id
        description: Business key in raw format
      - name: load_datetime
        description: Standard metadata column according to DV standards
      - name: record_source
        description: Standard metadata column according to DV standards

  - name: hub_contact
    description: Hub table for Contact entity
    columns:
      - name: contact_pk_hash
        description: Hash representation of the business key
        tests:
          - not_null
          - unique
      - name: contact_id
        description: Business key in raw format
      - name: load_datetime
        description: Standard metadata column according to DV standards
      - name: record_source
        description: Standard metadata column according to DV standards
      
  - name: hub_opportunity
    description: Hub table for Opportunity entity
    columns:
      - name: opportunity_pk_hash
        description: Hash representation of the business key
        tests:
          - not_null
          - unique
      - name: opportunity_id
        description: Business key in raw format
      - name: load_datetime
        description: Standard metadata column according to DV standards
      - name: record_source
        description: Standard metadata column according to DV standards

  - name: hub_lead
    description: Hub table for Lead entity
    columns:
      - name: lead_pk_hash
        description: Hash representation of the business key
        tests:
          - not_null
          - unique
      - name: lead_id
        description: Business key in raw format
      - name: load_datetime
        description: Standard metadata column according to DV standards
      - name: record_source
        description: Standard metadata column according to DV standards
